export const START_SAVE_TOKEN = 'START_SAVE_TOKEN';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const GET_TOKEN = 'GET_TOKEM';
export const LOGOUT = 'LOGOUT';

export const SAVE_USER = 'SAVE_USER';

export const START_GET_GROUPS = 'START_GET_GROUPS';
export const GET_GROUPS_EXITO = 'GET_GROUPS_EXITO';
export const GET_GROUPS_ERROR = 'GET_GROUPS_ERROR';

export const START_POST_GROUP = 'START_POST_GROUP';
export const POST_GROUP_EXITO = 'POST_GROUP_EXITO';
export const POST_GROUP_ERROR = 'POST_GROUP_ERROR';

export const START_PUT_GROUP = 'START_PUT_GROUP';
export const PUT_GROUP_EXITO = 'PUT_GROUP_EXITO';
export const PUT_GROUP_ERROR = 'PUT_GROUP_ERROR';

export const START_DELETE_GROUP = 'START_DELETE_GROUP';
export const DELETE_GROUP_EXITO = 'DELETE_GROUP_EXITO';
export const DELETE_GROUP_ERROR = 'DELETE_GROUP_ERROR';

export const START_GET_UNITS = 'START_GET_UNITS';
export const GET_UNITS_EXITO = 'GET_UNITS_EXITO';
export const GET_UNITS_ERROR = 'GET_UNITS_ERROR';

export const START_PUT_UNITS = 'START_PUT_UNITS';
export const PUT_UNITS_EXITO = 'PUT_UNITS_EXITO';
export const PUT_UNITS_ERROR = 'PUT_UNITS_ERROR';

export const START_GET_CMDS = 'START_GET_CMDS';
export const GET_CMDS_EXITO = 'GET_CMDS_EXITO';
export const GET_CMDS_ERROR = 'GET_CMDS_ERROR';

export const START_GET_JOBS = 'START_GET_JOBS';
export const GET_JOBS_EXITO = 'GET_JOBS_EXITO';
export const GET_JOBS_ERROR = 'GET_JOBS_ERROR';
export const START_UPDATE_UNITS_JOBS = 'START_UPDATE_UNITS_JOBS';
export const UPDATE_UNITS_JOBS_EXITO = 'UPDATE_UNITS_JOBS_EXITO';
export const UPDATE_UNITS_JOBS_ERROR = 'UPDATE_UNITS_JOBS_ERROR';
export const START_UPDATE_JOBS = 'START_UPDATE_JOBS';
export const UPDATE_JOBS_EXITO = 'UPDATE_JOBS_EXITO';
export const UPDATE_JOBS_ERROR = 'UPDATE_JOBS_ERROR';

export const LOGOUT_USUARIO = 'LOGOUT_USUARIO';
export const LOGOUT_UNIDADES = 'LOGOUT_UNIDADES';
export const LOGOUT_TAREAS = 'LOGOUT_TAREAS';
export const LOGOUT_GRUPOS = 'LOGOUT_GRUPOS';
export const LOGOUT_CMDS = 'LOGOUT_CMDS';